/// Zone-level alerts generated by [CrowdAnalysisService].
library;

import 'package:freezed_annotation/freezed_annotation.dart';
import 'congestion_level.dart';

part 'zone_alert.freezed.dart';
part 'zone_alert.g.dart';

/// Type of alert raised for a zone.
enum AlertType {
  /// Density exceeds LoS-E threshold.
  congestionWarning,

  /// Bottleneck score > 0.75 — flow gridlock imminent.
  bottleneckDetected,

  /// Anomaly flag from edge ML model.
  anomalyDetected,

  /// Predicted density at T+60s exceeds threshold.
  predictiveSurge,
}

@freezed
class ZoneAlert with _$ZoneAlert {
  const factory ZoneAlert({
    @JsonKey(name: 'zone_id') required String zoneId,
    @JsonKey(name: 'alert_type') required AlertType alertType,
    required CongestionLevel severity,
    required String message,
    @JsonKey(name: 'timestamp_ms') required int timestampMs,

    /// Whether an operator has acknowledged this alert.
    @Default(false) bool acknowledged,
  }) = _ZoneAlert;

  factory ZoneAlert.fromJson(Map<String, dynamic> json) =>
      _$ZoneAlertFromJson(json);
}
